export const HealthDataTypes = {
  // Dietary
  Biotin: 'DietaryBiotin',
  Caffeine: 'DietaryCaffeine',
  Calcium: 'DietaryCalcium',
  Carbohydrates: 'DietaryCarbohydrates',
  Chloride: 'DietaryChloride',
  Cholesterol: 'DietaryCholesterol',
  Chromium: 'DietaryChromium',
  Copper: 'DietaryCopper',
  EnergyConsumed: 'DietaryEnergyConsumed',
  FatMonounsaturated: 'DietaryFatMonounsaturated',
  FatPolyunsaturated: 'DietaryFatPolyunsaturated',
  FatSaturated: 'DietaryFatSaturated',
  FatTotal: 'DietaryFatTotal',
  Fiber: 'DietaryFiber',
  Folate: 'DietaryFolate',
  Iodine: 'DietaryIodine',
  Iron: 'DietaryIron',
  Magnesium: 'DietaryMagnesium',
  Manganese: 'DietaryManganese',
  Molybdenum: 'DietaryMolybdenum',
  Niacin: 'DietaryNiacin',
  PantothenicAcid: 'DietaryPantothenicAcid',
  Phosphorus: 'DietaryPhosphorus',
  Potassium: 'DietaryPotassium',
  Protein: 'DietaryProtein',
  Riboflavin: 'DietaryRiboflavin',
  Selenium: 'DietarySelenium',
  Sodium: 'DietarySodium',
  Sugar: 'DietarySugar',
  Thiamin: 'DietaryThiamin',
  VitaminA: 'DietaryVitaminA',
  VitaminB12: 'DietaryVitaminB12',
  VitaminB6: 'DietaryVitaminB6',
  VitaminC: 'DietaryVitaminC',
  VitaminD: 'DietaryVitaminD',
  VitaminE: 'DietaryVitaminE',
  VitaminK: 'DietaryVitaminK',
  Water: 'DietaryWater',
  Zinc: 'DietaryZinc',

  // Body
  Height: 'Height',
  BodyMass: 'BodyMass',
  BodyMassIndex: 'BodyMassIndex',
  LeanBodyMass: 'LeanBodyMass',
  BodyFatPercentage: 'BodyFatPercentage',
  WaistCircumference: 'WaistCircumference',
};

// SI units can be prefixed as follows:
// da   (deca-)   = 10                 d    (deci-)   = 1/10
// h    (hecto-)  = 100                c    (centi-)  = 1/100
// k    (kilo-)   = 1000               m    (milli-)  = 1/1000
// M    (mega-)   = 10^6               mc   (micro-)  = 10^-6
// G    (giga-)   = 10^9               n    (nano-)   = 10^-9
// T    (tera-)   = 10^12              p    (pico-)   = 10^-12
export const UnitTypes = {
  grams: 'g',
  miligrams: 'mg',
  kilograms: 'kg',
  meters: 'm',
  milimeters: 'mm',
  centimeters: 'cm',
  kilometers: 'km',
  liters: 'l',
  pascals: 'Pa',
  seconds: 's',
  joules: 'J',
  kelvin: 'K',
  siemens: 'S',
  hertz: 'hz',
  moles: 'mol',
  decibelHearingLevel: 'dBHL',
  celsius: 'degC',
  fahrenheit: 'degF',
  calories: 'cal',
  kilocalories: 'kcal',
  minutes: 'min',
  hours: 'hr',
  days: 'd',
  inches: 'in',
  feet: 'ft',
  miles: 'mi',
  ounces: 'oz',
  pounds: 'lb',
  stones: 'st',
  fluidOuncesImperial: 'fl_oz_imp',
  fluidOuncesUS: 'fl_oz_us',
  pintImperial: 'pt_imp',
  pintUS: 'pt_us',
  cupImperial: 'cup_us',
  cupUS: 'cup_imp',
};
